### ISSUE TITLE
Keeping lat lng in sync with Migrations?

### ISSUE THREAD

**Issue by karmicdice** [dereuromark/cakephp-geo#55]
I am using this plugin for a project where we baked a migration using latitude longitude (https://book.cakephp.org/migrations/2/en/index.html#columns-definition), turns out, I had to define in config
https://github.com/dereuromark/cakephp-geo/blob/master/src/Model/Behavior/GeocoderBehavior.php#L47:L48
It is not a major inconvenience but I propose to have a consistency with baked migrations...... if it doesn't result in breaking changes (which it will, I guess ! :100:  )

**Comment by dereuromark** [comment]
I dont follow.

**Comment by karmicdice** [comment]
Can we rename the config defaults?
From:

 ```
'lat' => 'lat', // Field name in your entity
'lng' => 'lng', // Field name in your entity
```

to

 ```
'latitude' => 'latitude', // Field name in your entity
'longitude' => 'longitude', // Field name in your entity
```

Example...

username and password are default - for Auth and it picks up automatically.

latitude and longitude can be baked by the migrations, so maybe we can default them?

**Comment by dereuromark** [comment]
I see, so the long names would be picked up my migrations/bake?
Couldn't we also add the short ones into them? They are quite commonly used I would say

Just changing the defaults now seems like a major change.
Especially since you can configure them quite easily

In your global app.php - or Configure::write('Geocoder', ...):
add those two lines and it is solved already for your whole app.

**Comment by karmicdice** [comment]
> Couldn't we also add the short ones into them? They are quite commonly used I would say

Yea that's cool too. I can see you have already created a PR on the migrations.

> Just changing the defaults now seems like a major change.

Yea, its not a major inconvience, but my request was to put more of consistency with stuff.
